version: '3'
services:

  redis:
    image: 'redis'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    container_name: 'amigo-cache'
    ports:
    - "6379:6379"